sudo: false
language: node_js
node_js:
  - '4.2.3'
env:
  global:
    secure: TWmpBzRG68b9e5wbJ7I6ox8TrZTnU/XpOkBvggJyuMgvUz27accp92Y9U7DWUPiXYXcWnoc7pqVAvEbwd1/ykHKCqezmyEXsrzZo6POg2lNFXkI9vSuDukL8A4Ct9zANVmr+5Y+kEBtQ/viyO5Rxc5H9bZskSeMaegqR60ZT2E8=

branches:
  only:
    - master
    - patch

before_install:
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH

before_script:
  - export DISPLAY=:99.0 # firefox virtual screen
  - sh -e /etc/init.d/xvfb start # firefox virtual screen
  - git config --global user.email "ngmaterial@googlegroups.com"
  - git config --global user.name "ngMaterial Bot"
  - mv $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs  /home/travis/build/angular/material/node_modules/karma-phantomjs2-launcher/node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs

script:
  # Fail builds which use iit/ddescribe, but run the tests anyways
  - gulp ddescribe-iit
  - gulp karma --reporters='dots'

after_success:
  - ./scripts/travis-build-init.sh --sha=$TRAVIS_COMMIT

notifications:
  flowdock: ca58afe1354053b15fe75a763138829d


